Add eduGAIN registration content to README
ausaccessfed/saml-service pull request #234
Opened 2020-10-15 05:44 UTC by bradleybeddoes

Requesting review by all of @ausaccessfed/developers simply so you know how to do this if I am not around.

2020-10-15 22:46 UTC, rianniello approved these changes

2020-10-15 22:58 UTC, mikelkew commented
LGTM, extra documentation definitely helpful. Curious to know if there's any specific reason this can't be simplified with 2 rake tasks though?

2020-10-15 22:59 UTC, chrisjones120 approved these changes

2020-10-15 23:05 UTC, rcaught requested changes
Can we use `!` bang methods on all `create` and `save` calls?

2020-10-16 00:05 UTC, bradleybeddoes commented
> Can we use `!` bang methods on all `create` and `save` calls?

Your command is my wish sir @rcaught - https://github.com/ausaccessfed/saml-service/pull/234/commits/b5da992c43c1d3c0c70239036df4dffc43ecc751

2020-10-16 00:06 UTC, bradleybeddoes commented
> Curious to know if there's any specific reason this can't be simplified with 2 rake tasks though?

A toxic combination of "we've always done it this way" and laziness.

Let me have a poke around, should be doable.

2020-10-16 02:30 UTC, bradleybeddoes commented
To make sir @mikelkew happy I have provided rake tasks for this now, he'll love them. 

README updated.

Have validated all logic against test federation SAML service and ensured flows through to metadata. Unit tests will have to be a thing for another day though.

2020-10-16 02:47 UTC, rcaught requested changes
If I say the rake tasks are missing bangs will you hate me?

2020-10-16 02:47 UTC, mikelkew commented
> To make sir @mikelkew happy I have provided rake tasks for this now, he'll love them.

Nice one, that I do!

Noting also that `raise_on_save_failure` is true be default for `create`/`save` in Sequel @rcaught.

2020-10-16 02:48 UTC, rcaught commented
> > To make sir @mikelkew happy I have provided rake tasks for this now, he'll love them.
> 
> Nice one, that I do!
> 
> Noting also that `raise_on_save_failure` is true by default for `create`/`save` in Sequel @rcaught.

Oh right!

2020-10-16 03:04 UTC, mikelkew commented on README.md
> +1. Run `rake edugain:publish_sp\['https://example.edu.au/shibboleth','https://example.edu.au/information_url'\]` replacing `https://example.edu/shibboleth` with the target EntityID
Escaping the square brackets doesn't seem to be necessary for me in `zsh`, `bash` or `sh`, but I guess no harm to use them regardless.

2020-10-16 03:18 UTC, bradleybeddoes commented
> Noting also that `raise_on_save_failure` is [true by default](https://sequel.jeremyevans.net/rdoc/classes/Sequel/Model/ClassMethods.html#attribute-i-raise_on_save_failure)

Yep, relying on this for the most part but then being explicit in the final `save` to be 100% sure.

2020-10-16 04:16 UTC, mikelkew approved these changes

2020-10-16 04:20 UTC, rianniello approved these changes

2020-10-19 01:28 UTC, rcaught approved these changes

2020-10-19 01:43 UTC, merged