Upgrades/rails 6 1 4 4
ausaccessfed/saml-service pull request #267
Opened 2022-02-25 08:08 UTC by waldofouche

2022-02-28 05:35 UTC, waldofouche commented
Dropping d73c3f1 and 4aa0db3 since they cuase an obsurd amount of tests to break ~160. leaving a reference to them though as they could be useful

2022-02-28 06:05 UTC, waldofouche commented
Currently only failing 6 specs: 

```
Finished in 6 minutes 13 seconds (files took 5.59 seconds to load)
2085 examples, 6 failures

Failed examples:

rspec ./spec/controllers/metadata_query_controller_spec.rb:188 # MetadataQueryController#all_entities GET valid client request MetadataInstance does allow rendering all entities initial request uncached server side cache updates server side cache
rspec ./spec/controllers/metadata_query_controller_spec.rb:659 # MetadataQueryController#tagged_entities GET valid client request MetadataInstance has entities matching tag initial request uncached server side cache updates server side cache
rspec './spec/controllers/metadata_query_controller_spec.rb[1:2:1:1:1:1:1:1:1:2:1]' # MetadataQueryController#specific_entity With URI identifier EntityDescriptor GET valid client request valid entity_descriptor initial request uncached server side cache updates server side cache
rspec './spec/controllers/metadata_query_controller_spec.rb[1:2:1:2:1:1:1:1:1:2:1]' # MetadataQueryController#specific_entity With URI identifier RawEntityDescriptor GET valid client request valid entity_descriptor initial request uncached server side cache updates server side cache
rspec './spec/controllers/metadata_query_controller_spec.rb[1:2:2:2:1:1:1:1:1:2:1]' # MetadataQueryController#specific_entity With sha1 identifier RawEntityDescriptor GET valid client request valid entity_descriptor initial request uncached server side cache updates server side cache
rspec './spec/controllers/metadata_query_controller_spec.rb[1:2:2:1:1:1:1:1:1:2:1]' # MetadataQueryController#specific_entity With sha1 identifier EntityDescriptor GET valid client request valid entity_descriptor initial request uncached server side cache updates server side cache
```

Not sure why, been a bit stuck trying to troubleshoot. My best guess is it is related to some change made in cc9ad75

2022-03-02 02:03 UTC, waldofouche commented
I realised when I ran `rubocop -A` it was using the latest version on my system, and addressing all those errors caused major problems. The correct command was `bundle exec rubocop -a`

2022-03-04 02:49 UTC, waldofouche commented
Hmm, something odd happening here, 86d71fb has passed on re-runs but not the first run. Have force pushed it but still failing

https://ap-southeast-2.console.aws.amazon.com/codesuite/codebuild/926857881019/projects/saml-service/build/saml-service%3A121125fd-f9e2-4a3b-a2ab-ede6cb6a4b15?region=ap-southeast-2

2022-03-09 05:40 UTC, waldofouche commented
Based on @rianniello previous testing: 

```
[1] pry(main)> FactoryBot::create :idp_sso_descriptor
=> #<IDPSSODescriptor @values={:id=>4, :entity_descriptor_id=>4, :organization_id=>nil, :error_url=>nil, :extensions=>nil, :created_at=>2022-03-09 05:33:59 UTC, :updated_at=>2022-03-09 05:33:59 UTC, :kind=>"IDPSSODescriptor", :enabled=>true, :want_authn_requests_signed=>false}>
[2] pry(main)> FactoryBot::create :sp_sso_descriptor
=> #<SPSSODescriptor @values={:id=>5, :entity_descriptor_id=>5, :organization_id=>nil, :error_url=>nil, :extensions=>nil, :created_at=>2022-03-09 05:34:16 UTC, :updated_at=>2022-03-09 05:34:16 UTC, :kind=>"SPSSODescriptor", :enabled=>true, :authn_requests_signed=>false, :want_assertions_signed=>false}>
[3] pry(main)> FactoryBot::create :sp_sso_descriptor
=> #<SPSSODescriptor @values={:id=>6, :entity_descriptor_id=>6, :organization_id=>nil, :error_url=>nil, :extensions=>nil, :created_at=>2022-03-09 05:34:32 UTC, :updated_at=>2022-03-09 05:34:32 UTC, :kind=>"SPSSODescriptor", :enabled=>true, :authn_requests_signed=>false, :want_assertions_signed=>false}>
```

```
~ curl http://localhost:8080/api/discovery/entities

{"identity_providers":[{"entity_id":"http://johns.co/lida/shibboleth","tags":[],"names":[],"logos":[],"descriptions":[],"single_sign_on_endpoints":{"soap":[]},"geolocations":[],"domains":[]}],"service_providers":[{"entity_id":"http://king.com/marylin_cartwright/shibboleth","tags":[],"names":[],"logos":[],"descriptions":[],"all_discovery_response_endpoints":[],"information_urls":[],"privacy_statement_urls":[]},{"entity_id":"http://lind.io/joey_boyer/shibboleth","tags":[],"names":[],"logos":[],"descriptions":[],"all_discovery_response_endpoints":[],"information_urls":[],"privacy_statement_urls":[]}]}%
```
I also attempted: 
```
➜  ~ http http://localhost:8080/mdq/JMWhTb1X01EB_4gZ0zUfOQ/entities Accept:application/samlmetadata+xml
HTTP/1.1 404 Not Found
Cache-Control: max-age=600, private
Content-Type: text/html
Date: Wed, 09 Mar 2022 05:39:35 GMT
Referrer-Policy: strict-origin-when-cross-origin
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: ff3a2032-6b81-4a7f-b0a5-d020a77694c6
X-Runtime: 0.002850
X-XSS-Protection: 1; mode=block


➜  ~
```
But was unsure of how to locate the correct id to replace `JMWhTb1X01EB_4gZ0zUfOQ` after some digging

2022-03-09 05:42 UTC, waldofouche commented
Ready for final review here @rianniello

2022-03-11 00:49 UTC, rianniello commented
@waldofouche see what other `MetadataInstance` you have lying around. (Perhaps made with that first call)

2022-03-15 00:23 UTC, rianniello commented on config/puma.rb
> +pidfile     ENV.fetch('PIDFILE', 'tmp/pids/server.pid')
Will still likely work (reference here: https://github.com/ausaccessfed/aaf-ansible/blob/develop/roles/saml/tasks/main.yml#L41) but may be cleaner just to reuse existing pidfile per old puma.rb `tmp/pids/puma.pid`

2022-03-15 00:24 UTC, rianniello commented on config/puma.rb
> +# workers ENV.fetch("WEB_CONCURRENCY", 2)
I would recommend leaving the workers/threads numbers as before. Having `1,1` threads and 3x workers smells of concurrency issues we're trying to hide. 😢

2022-03-15 00:30 UTC, rianniello commented on config/deploy.yml.dist
> -  bind: tcp://0.0.0.0:8080
This is the real one btw, which require aaf-ansible changes https://github.com/ausaccessfed/aaf-ansible/blob/develop/roles/saml/templates/deploy.yml.j2

2022-03-15 00:31 UTC, rianniello commented on config/puma.rb
> +persistent_timeout 75
NWO specific thing, but won't hurt to have this here.

2022-03-15 00:35 UTC, rianniello commented on config/puma.rb
> -stdout_redirect puma_config['stdout'],
Would be wise to also retain stdout_redirect configuration, just to keep things consistent in OWO

2022-03-15 01:23 UTC, waldofouche commented on config/puma.rb
> +pidfile     ENV.fetch('PIDFILE', 'tmp/pids/server.pid')
Sure thing! I will fix this up to use the existing one in `tmp/pids/puma.pid`

2022-03-15 01:24 UTC, waldofouche commented on config/puma.rb
> +# workers ENV.fetch("WEB_CONCURRENCY", 2)
Ah, shame :( Will revert to only having `1,1`

2022-03-15 02:15 UTC, waldofouche commented on config/puma.rb
> +pidfile     ENV.fetch('PIDFILE', 'tmp/pids/server.pid')
c51b682

2022-03-15 02:15 UTC, waldofouche commented on config/puma.rb
> +# workers ENV.fetch("WEB_CONCURRENCY", 2)
e72245e

2022-03-15 02:15 UTC, waldofouche commented on config/puma.rb
> -stdout_redirect puma_config['stdout'],
fixed up in 5242c9

2022-03-15 02:16 UTC, waldofouche commented on config/deploy.yml.dist
> -  bind: tcp://0.0.0.0:8080
Ah thanks! Will create a subsequent PR for it there!

2022-03-15 02:49 UTC, waldofouche commented on config/deploy.yml.dist
> -  bind: tcp://0.0.0.0:8080
Created the PR https://github.com/ausaccessfed/aaf-ansible/pull/993

2022-03-17 01:44 UTC, waldofouche commented on config/deploy.yml.dist
> -  bind: tcp://0.0.0.0:8080
@matthew-puku caught the error I made here, I accidently set the `config` to use `port` instead of `bind` when trying to get it to boot up, see https://github.com/ausaccessfed/aaf-ansible/pull/993#issuecomment-1069818200

2022-03-17 23:09 UTC, matthew-puku requested changes

2022-03-17 23:09 UTC, matthew-puku commented on config/environments/production.rb
> -  Sequel::Deprecation.output = false
Keep this line? Can't imagine we'd want the sequel spam in our production logs.

2022-03-17 23:09 UTC, matthew-puku commented on config/puma.rb
> -tag 'saml'
Keep this line?

2022-03-17 23:09 UTC, matthew-puku commented on config/deploy.yml.dist
> +  port: tcp://127.0.0.1:8080
Don't see any good reason to rename this to `port`, since it will be `bind` in ansible land.

2022-03-17 23:09 UTC, matthew-puku commented on config/puma.rb
> +bind ENV.fetch('PORT', puma_config['port'])
I think this is `puma_config['bind']` in ansible land, we should change it back

2022-03-18 01:18 UTC, waldofouche commented on config/deploy.yml.dist
> +  port: tcp://127.0.0.1:8080
Fixed up in b068484

2022-03-18 01:18 UTC, waldofouche commented on config/puma.rb
> +bind ENV.fetch('PORT', puma_config['port'])
Fixed up in b068484

2022-03-18 01:19 UTC, waldofouche commented on config/environments/production.rb
> -  Sequel::Deprecation.output = false
Fixed up in 82f1746

2022-03-18 01:19 UTC, waldofouche commented on config/puma.rb
> -tag 'saml'
Fixed up in https://github.com/ausaccessfed/saml-service/commit/b068484acf57a89a5f53ddaa51e4e4ff2a00e758

2022-03-18 01:37 UTC, matthew-puku approved these changes
Awesome!

2022-03-18 04:45 UTC, rianniello commented on config/environments/production.rb
> -  Sequel::Deprecation.output = false
👍

2022-03-18 04:46 UTC, rianniello approved these changes
LGTM, For monday 👍

2022-03-18 04:58 UTC, ArthurZheng approved these changes
👍

2022-03-22 03:03 UTC, waldofouche commented
Ah I forgot to push this out! I'll push tomorrow morning

2022-03-23 00:57 UTC, merged

2022-03-23 04:04 UTC, vladimir-mencl-eresearch commented
Hi guys,

I've just tried rolling this into our DEV environment and got an error:
```
Your bundle only supports platforms ["x86_64-darwin-20"] but your local platform
is x86_64-linux. Add the current platform to the lockfile with
`bundle lock --add-platform x86_64-linux` and try again.
```

and indeed, Gemfile.lock only has:
```
PLATFORMS
  x86_64-darwin-20
```

I think it might have surfaced only now because this PR switches the bundler version from 1.x to 2.x (1.17.2 to 2.3.9) - and our tooling deploys with the same version of bundler as what's recorded in Gemfile.lock...
Sorry, needs some cleanup....

2022-03-23 08:14 UTC, waldofouche commented
Hi @vladimir-mencl-eresearch, 

Sorry about that! I addressed it before in another app, but looks like I missed it here, I have created https://github.com/ausaccessfed/saml-service/pull/270 to add it in