Testing if reducing the amount of duplicate test runs has any bearing on speed
ausaccessfed/saml-service pull request #313
Opened 2022-10-20 04:30 UTC by phyzical

2022-10-20 05:12 UTC, matthew-puku commented on spec/support/jobs/concerns/etl/common.rb
>      it 'updates name id formats' do
I think it'd be worthwhile to update these descriptions to reflect the broader scope of the assertions. I see you have done that in some places already so maybe you were intending to come back to these anyway.

2022-10-20 05:14 UTC, phyzical commented on spec/support/jobs/concerns/etl/common.rb
>      it 'updates name id formats' do
yeah  i agree, and your right i just left it alone to get some benchmark timings before putting the effort

2022-10-20 05:21 UTC, ArthurZheng commented on spec/support/jobs/concerns/etl/common.rb
> -
👍 ++

2022-10-24 06:30 UTC, matthew-puku requested changes
will work thru now and nit the it blocks. Shouldn't be long

2022-10-24 06:30 UTC, matthew-puku commented on spec/support/jobs/concerns/etl/attribute_authorities.rb
> +        it 'sets scopes and regex to false' do
```suggestion
        it 'sets scope and sets regex to false' do
```

2022-10-24 06:33 UTC, matthew-puku commented on spec/support/jobs/concerns/etl/endpoints.rb
> +  it 'expected data' do
```suggestion
  it 'sets expected data' do
```

2022-10-24 06:33 UTC, matthew-puku commented on spec/support/jobs/concerns/etl/endpoints.rb
> +  it 'expected data' do
```suggestion
  it 'sets expected data' do
```

2022-10-24 06:34 UTC, matthew-puku commented on spec/support/jobs/concerns/etl/identity_providers.rb
> +  # rubocop:enable  Metrics/MethodLength,Metrics/AbcSize
```suggestion
  # rubocop:enable Metrics/MethodLength,Metrics/AbcSize
```

2022-10-24 06:34 UTC, matthew-puku commented on spec/support/jobs/concerns/etl/identity_providers.rb
> +        it 'sets a scope and refex to false' do
```suggestion
        it 'sets a scope with regexp: false' do
```

2022-10-24 06:35 UTC, matthew-puku commented on spec/support/jobs/concerns/etl/identity_providers.rb
> +    it 'Works as expected, sets scope, doesnt make tags, updates sso, assertion id, attribute profile and attributes' do
```suggestion
    it 'works as expected, sets scope, doesnt make tags, updates sso, assertion id, attribute profile and attributes' do
```

2022-10-24 06:36 UTC, matthew-puku commented on spec/support/jobs/concerns/etl/service_providers.rb
> -    it 'updates attribute_consuming_services' do
lol why was this down here

2022-10-24 06:38 UTC, matthew-puku commented on spec/support/metadata/contact_person.rb
> +      it 'is created has correct value' do
```suggestion
      it 'is created with correct value' do
```

2022-10-24 06:38 UTC, matthew-puku commented on spec/support/metadata/contact_person.rb
> +      it 'is created has correct value' do
```suggestion
      it 'is created with correct value' do
```

2022-10-24 06:38 UTC, matthew-puku commented on spec/support/metadata/contact_person.rb
> +      it 'is created has correct value' do
```suggestion
      it 'is created with correct value' do
```

2022-10-24 06:40 UTC, matthew-puku commented on spec/support/metadata/contact_person.rb
> +      it 'is created has correct value' do
```suggestion
      it 'is created with correct value' do
```

2022-10-24 06:40 UTC, matthew-puku commented on spec/support/metadata/contact_person.rb
> +      it 'is created has correct value' do
```suggestion
      it 'is created with correct value' do
```

2022-10-24 06:40 UTC, matthew-puku commented on spec/support/metadata/endpoint.rb
> +    context 'ResponseLocation when populated' do
```suggestion
    context 'when ResponseLocation is populated' do
```

2022-10-24 06:40 UTC, matthew-puku commented on spec/support/metadata/endpoint.rb
> +    it 'has binding, location' do
```suggestion
    it 'has binding and location' do
```

2022-10-24 06:40 UTC, matthew-puku commented on spec/support/metadata/endpoint.rb
> +      it 'is rendered, location' do
```suggestion
      it 'is rendered and has location' do
```

2022-10-24 06:40 UTC, matthew-puku commented on spec/support/metadata/entities_descriptor.rb
> +      it 'sets ID and name and validuntil' do
```suggestion
      it 'sets ID, name and validuntil' do
```

2022-10-24 06:43 UTC, matthew-puku commented on spec/support/metadata/mdui_ui_info.rb
> +      it 'sets languageand text' do
```suggestion
      it 'sets language and text' do
```

2022-10-24 06:43 UTC, matthew-puku commented on spec/support/metadata/mdui_ui_info.rb
> +      it 'sets language, text' do
```suggestion
      it 'sets language and text' do
```

2022-10-24 06:48 UTC, matthew-puku commented on spec/support/metadata/signature.rb
> -  end
this one is pretty cryptic. Without the it description I have no idea what this assertion is for. Maybe it should go back. Or you could put a comment within the block

2022-10-24 06:50 UTC, matthew-puku commented on spec/support/metadata/sp_sso_descriptor.rb
> +    it 'is not rendered' do
```suggestion
    it 'are not rendered' do
```

2022-10-24 06:51 UTC, matthew-puku commented on spec/support/metadata/sso_role_descriptor.rb
> +  it 'is created without sso, name_id and artificat resolution' do
```suggestion
  it 'is created without sso, name_id and artifact resolution' do
```

2022-10-24 06:53 UTC, matthew-puku approved these changes
Much more readable overall already tbh but may as well fix the typos

2022-10-24 08:30 UTC, phyzical commented on spec/support/metadata/signature.rb
> -  end
added some inline comments to try to preserve some of the it blocks futher

2022-10-24 08:37 UTC, merged